head(iris,150)
xdata=iris$Sepal.Length
MinQ=quantile(xdata,0)
FQ=quantile(xdata,0.25)
SQ=quantile(xdata,0.5)
TQ=quantile(xdata,0.75)
MaxQ=quantile(xdata,1)
cat("Minimum",MinQ)
cat("Lower Quartile",FQ)
cat("Median",SQ)
cat("Upper Quartile",TQ)
cat("Maximum",MaxQ)
AQ=quantile(xdata,prob=c(0,0.25,0.5,0.75,1))
cat("All the quartiles",AQ)
summary(xdata)
boxplot(xdata,main="Inter Quartile Range for sepal length",ylab="centimeters")
as.numeric(quantile(xdata,0.75)-quantile(xdata,0.25))
IQR(xdata)
